#!/usr/bin/env php
<?php

require_once('vendor/autoload.php');

use Symfony\Component\Process\Process;
use Symfony\Component\Process\Exception\ProcessFailedException;

if(empty($argv[1]) || (!empty($argv[2]) && $argv[2] === 'list')) {
    echo "\n";
    echo "Notch, v0.1 \n\n";
    echo "Available commands:\n";
    echo "   serve - Start the development server and task runner.\n";
    echo "   build - Generate static theme assets for production.\n";
    echo "   make:theme - Scaffold a new theme.\n";
    echo "\n";
}

if(!empty($argv[1]) && $argv[1] === 'serve') {
    $process = new Process('npm run dev');

    $process->run(function ($type, $buffer) {
        echo $buffer;
    });
}

if(!empty($argv[1]) && $argv[1] === 'build') {
    $process = new Process('npm run production');

    $process->run(function ($type, $buffer) {
        echo $buffer;
    });
}

if(!empty($argv[1]) && strpos($argv[1], 'make') !== false) {
    $scaffold_args = explode(':', $argv[1]);

    if(!empty($scaffold_args[1])) {
        if($scaffold_args[1] === 'theme' && !empty($argv[2])) {
            echo "{$argv[2]} theme built!\n";
        }
    }
}

exit();
